/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConnectionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marlon 1
 */
public class InterfazEditarAfiliado extends javax.swing.JInternalFrame {

    String cedulaUsuario;
    private String cont ;

    /**
     * Creates new form InterfazEditarAfiliado
     */
    public InterfazEditarAfiliado() throws SQLException {
        initComponents();
        jpanelCambiarCon.setVisible(false);
        cargarDatos();
    }
    public InterfazEditarAfiliado(String cedula) throws SQLException {   
        initComponents();
        cedulaUsuario=cedula;
        jpanelCambiarCon.setVisible(false);
        cargarDatos();
    }

   

    public void cargarDatos() throws SQLException {
        ConnectionDB cn = new ConnectionDB();
        Connection cc = cn.getConnection();
        String datos[] = new String[4];
        String sql = "";
        sql = "select * from usuarios where CED_USU='" + cedulaUsuario + "'";
        //sql = "select * from usuarios where CED_USU='1804149233'";
        Statement psd = cc.createStatement();
        ResultSet rs = psd.executeQuery(sql);
        while (rs.next()) {
            datos[0] = rs.getString("CED_USU");
            datos[1] = rs.getString("NOM_USU");
            datos[2] = rs.getString("APE_USU");
            datos[3] = rs.getString("CONT_USU");

        }
        jtxtCedula.setText(datos[0]);
        jtxtNombre.setText(datos[1]);
        jtxtApellido.setText(datos[2]);
        
        jtxtCedula.setEditable(false);
        jtxtNombre.setEditable(false);
        jtxtApellido.setEditable(false);
        cont = datos[3];

    }

    public boolean Guardar() {
        if (jtxtConN.getText().isEmpty()) {
            jtxtConN.requestFocus();
        } else if (jtxtConC.getText().isEmpty()) {
            jtxtConC.requestFocus();
        } else {
            String contraNueva = jtxtConN.getText();
            String contraConfi = jtxtConC.getText();
            if (contraNueva.equals(contraConfi)) {
                ConnectionDB cn = new ConnectionDB();
                Connection cc = cn.getConnection();
                String sql = "";
                sql = "UPDATE set CONT_USU='+" + contraConfi + "' where CED_USU='" + cedulaUsuario + "'";
                int condicion = JOptionPane.showConfirmDialog(this, "Seguro que desea cambiar la contraseña", "Actualizar", JOptionPane.YES_NO_CANCEL_OPTION);
                if (condicion > 0) {
                    PreparedStatement psd;
                    try {
                        psd = cc.prepareStatement(sql);
                        int com = psd.executeUpdate();
                        if (com > 0) {
                            JOptionPane.showMessageDialog(null, "Actualizado");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(InterfazEditarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
            }
        }

        return false;
    }

    public static String getSHA1(String contrasenia) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA1");
            byte[] array = md.digest(contrasenia.getBytes());
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1, 3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            System.out.println(e.getMessage());
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpanelCambiarCon = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtConA = new javax.swing.JTextField();
        jbtnG = new javax.swing.JButton();
        jtxtConN = new javax.swing.JTextField();
        jtxtConC = new javax.swing.JTextField();
        jbtnCC = new javax.swing.JButton();
        jtxtCedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PERFIL");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("APELLIDO:");

        jLabel4.setText("CEDULA:");

        jLabel5.setText("CONTRASEÑA ACTUAL :");

        jLabel6.setText("CONTRASEÑA NUEVA :");

        jLabel7.setText("CONFIRMAR CONTRASEÑA  :");

        jtxtConA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtConAFocusLost(evt);
            }
        });

        jbtnG.setText("GUARDAR");
        jbtnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelCambiarConLayout = new javax.swing.GroupLayout(jpanelCambiarCon);
        jpanelCambiarCon.setLayout(jpanelCambiarConLayout);
        jpanelCambiarConLayout.setHorizontalGroup(
            jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCambiarConLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCambiarConLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(452, 452, 452))
                    .addGroup(jpanelCambiarConLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(279, 279, 279))))
            .addGroup(jpanelCambiarConLayout.createSequentialGroup()
                .addGroup(jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCambiarConLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(48, 48, 48)
                        .addGroup(jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtConA, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jtxtConN)
                            .addComponent(jtxtConC)))
                    .addGroup(jpanelCambiarConLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jbtnG, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelCambiarConLayout.setVerticalGroup(
            jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCambiarConLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtxtConA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtConN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelCambiarConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtConC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnG)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jbtnCC.setText("CAMBIAR  CONTRASEÑA");
        jbtnCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpanelCambiarCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtNombre)
                                    .addComponent(jtxtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jtxtCedula)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jbtnCC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jbtnCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelCambiarCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCCActionPerformed

        jpanelCambiarCon.setVisible(true);
        jtxtConC.setEnabled(false);
        jbtnG.setEnabled(false);
        try {
            cargarDatos();
        } catch (SQLException ex) {
            Logger.getLogger(InterfazEditarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnCCActionPerformed

    private void jbtnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGActionPerformed
        Guardar();
    }//GEN-LAST:event_jbtnGActionPerformed

    private void jtxtConAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtConAFocusLost
        String contraActual = jtxtConA.getText();
        if (contraActual.equals(cont)) {
            jtxtConN.setEnabled(true);
            jtxtConC.setEnabled(true);
            jbtnG.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "La contraseña es incorrecta");
        }

    }//GEN-LAST:event_jtxtConAFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazEditarAfiliado().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazEditarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnCC;
    private javax.swing.JButton jbtnG;
    private javax.swing.JPanel jpanelCambiarCon;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtConA;
    private javax.swing.JTextField jtxtConC;
    private javax.swing.JTextField jtxtConN;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
