USUARIOS(CED_USU,CONT_USU,ROL_USU,NOM_USU,APE_USU,DIR_X,DIR_Y,DIR_USU_NORMAL) 
NEGOCIOS(RUC_NEG,CED_USU_PER,CAT_NEG,NOM_NEG,DIR_NEG_NORMAL,DIR_X_NEG,DIR_Y_NEG,CIU_NEG,PRO_NEGOCIO) 
CATEGORIAS(ID_CAT,NOM_CAT)
PRODUCTOS(ID_PRO,NOM_PRO,MAR_PRO,PRE_PRO,CAN_PRO,FEC_VEN_PRO,RUC_NEG_PER)
RESERVAS(NUM_RES,RUC_NEG,CED_USU,FEC_RES,VAL_TOT_RES)
DETALLE_RESERVA(NUM_DET,ID_PRO,CAN_PRO,SUB_TOTAL,NUM_RES_PER)

CREATE TABLE USUARIOS(

);